apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-server-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: my-storage-class
  gcePersistentDisk:
    pdName: sql-server-disk
    fsType: ext4
