apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server
spec:
  serviceName: sql-server
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:2022-latest
          resources: {}
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-password
                  key: password
          volumeMounts:
            - name: sql-server-volume
              mountPath: /var/opt/mssql
      volumes:
        - name: sql-server-volume
          persistentVolumeClaim:
            claimName: sql-server-pvc
  volumeClaimTemplates:
    - metadata:
        name: sql-server-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: my-storage-class
        resources:
          requests:
            storage: 5Gi
